import pandas as pd
import os
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

class ReportGenerator:
    def __init__(self, logger, config):
        self.logger = logger
        self.config = config
        self.reports_dir = config.get("paths", {}).get("reports", "reports")
        os.makedirs(self.reports_dir, exist_ok=True)

    def generate_report(self, df: pd.DataFrame, stats: dict, anomalies: pd.DataFrame, filename: str):
        """
        Generates a Markdown report with statistics, anomalies, and optional charts.
        """
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            report_name = f"{filename}_{timestamp}_report.md"
            report_path = os.path.join(self.reports_dir, report_name)

            with open(report_path, "w") as f:
                # Header
                f.write(f"# Data Pipeline Report\n\n")
                f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                f.write(f"**Source File:** {filename}\n\n")
                f.write(f"**Total Rows:** {len(df)}\n\n")
                f.write("---\n\n")

                # Statistics Section
                f.write("## Summary Statistics\n\n")
                if stats:
                    for col, col_stats in stats.items():
                        f.write(f"### {col}\n\n")
                        f.write("| Metric | Value |\n")
                        f.write("|--------|-------|\n")
                        for metric, value in col_stats.items():
                            f.write(f"| {metric.capitalize()} | {value:.2f} |\n")
                        f.write("\n")
                else:
                    f.write("*No numeric columns found for statistical analysis.*\n\n")

                # Anomalies Section
                f.write("## Anomaly Detection\n\n")
                if len(anomalies) > 0:
                    f.write(f"**Total Anomalies Detected:** {len(anomalies)}\n\n")
                    f.write(anomalies.to_markdown(index=False))
                    f.write("\n\n")
                else:
                    f.write("*No anomalies detected.*\n\n")

                # Data Preview
                f.write("## Data Preview (First 10 Rows)\n\n")
                f.write(df.head(10).to_markdown(index=False))
                f.write("\n\n")

                f.write("---\n")
                f.write("*Report generated by Automated Data Pipeline Tool*\n")

            self.logger.info(f"Report generated: {report_path}")
            
            # Generate charts if numeric columns exist
            self._generate_charts(df, filename, timestamp)
            
            return report_path

        except Exception as e:
            self.logger.error(f"Error generating report: {e}")
            raise

    def _generate_charts(self, df: pd.DataFrame, filename: str, timestamp: str):
        """
        Generates distribution charts for numeric columns.
        """
        try:
            numeric_cols = df.select_dtypes(include=['number']).columns
            if len(numeric_cols) == 0:
                self.logger.info("No numeric columns to chart.")
                return

            # Create a figure with subplots
            n_cols = len(numeric_cols)
            fig, axes = plt.subplots(n_cols, 1, figsize=(10, 4 * n_cols))
            if n_cols == 1:
                axes = [axes]

            for idx, col in enumerate(numeric_cols):
                sns.histplot(df[col], kde=True, ax=axes[idx])
                axes[idx].set_title(f"Distribution of {col}")
                axes[idx].set_xlabel(col)
                axes[idx].set_ylabel("Frequency")

            plt.tight_layout()
            chart_path = os.path.join(self.reports_dir, f"{filename}_{timestamp}_charts.png")
            plt.savefig(chart_path, dpi=150, bbox_inches='tight')
            plt.close()

            self.logger.info(f"Charts saved: {chart_path}")

        except Exception as e:
            self.logger.warning(f"Could not generate charts: {e}")
